version: '3.8'

services:

  nodeodm:
    image: opendronemap/nodeodm:latest
    ports:
      - "3000:3000"
    volumes:
      - nodeodm-data:/var/www/data
    environment:
      - PORT=3000
      - HOSTNAME=nodeodm
      - MAX_IMAGES=500
      - MAX_WORKERS=2
    networks:
      - skystore-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skystore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - skystore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skystore"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: ["postgres", "-c", "logging_collector=on"]

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=skystore
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=skystore
      - INFLUXDB_USER_PASSWORD=skystore
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - skystore-network
    healthcheck:
      test: ["CMD", "influx", "-execute", "SHOW DATABASES"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  chronograf:
    image: chronograf:latest
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    depends_on:
      - influxdb
    networks:
      - skystore-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9500
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - NODEODM_URL=http://nodeodm:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skystore
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/skystore
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DB=skystore
      - INFLUXDB_USER=skystore
      - INFLUXDB_PASSWORD=skystore
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      influxdb:
        condition: service_healthy
    networks:
      - skystore-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - skystore-network
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS="--appendonly yes"
   # volumes:
     # - redis-data:/data
    networks:
      - skystore-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9500:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - skystore-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  otel-collector:
    image: signoz/signoz-otel-collector:0.88.7
    ports:
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP http receiver
    networks:
      - skystore-network
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:23.11.2-alpine
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9181:9181"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - skystore-network
    restart: unless-stopped

  query-service:
    image: signoz/query-service:0.35.1
    ports:
      - "6060:6060"
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
    depends_on:
      - clickhouse
    networks:
      - skystore-network
    restart: unless-stopped

  frontend:
    image: signoz/frontend:0.35.1
    ports:
      - "3301:3301"
    depends_on:
      - query-service
    networks:
      - skystore-network
    restart: unless-stopped

networks:
  skystore-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  minio-data:
    driver: local
  nodeodm-data:
    driver: local
  clickhouse-data:
  postgres-data:
    driver: local
  influxdb-data:
    driver: local