$schema: 'https://moonrepo.dev/schemas/tasks.json'
fileGroups:
  docker-compose:
  - 'docker-compose.yml'

tasks:
  build:
    script: 'docker compose -f @in(0) build'
    options:
     # runFromWorkspaceRoot: true
      mergeInputs: append
    inputs:
    - '@files(docker-compose)'

  down:
    script: 'docker compose -f @in(0) down'
    options:
      #runFromWorkspaceRoot: true
      mergeInputs: append
    inputs:
      - '@files(docker-compose)'

  up:
    script: 'docker compose -f @in(0) up -d'
    options:
      runFromWorkspaceRoot: true
      mergeInputs: replace
    inputs:
      - '@files(docker-compose)'  
