$schema: 'https://moonrepo.dev/schemas/tasks.json'
fileGroups:
  docker:
  - 'Dockerfile'

tasks:
  docker-build:
    script: 'docker build -t @meta(tag):latest -f @files(docker) .'
    options:
      runFromWorkspaceRoot: true
    inputs:
    - '@files(docker)'

  docker-run:
    script: 'docker run -d @meta(tag):latest'
    options:
      runFromWorkspaceRoot: true
    inputs:
    - '@files(docker)'

  docker-dev:
    script: 'docker run --net=host @meta(tag):latest'
    options:
      runFromWorkspaceRoot: true
      interactive: true
    deps:
    - '~:docker-build'
    inputs:
    - '@files(docker)'

  down-all:
    script: 'docker kill $(docker ps -q)'
    description: 'Stop all running containers'
    options:
      runFromWorkspaceRoot: true
