name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Proto
        uses: moonrepo/setup-proto@v1
        
      - name: Install Moon
        run: proto install moon
        
      - name: Install Bun
        run: proto install bun
        
      - name: Install dependencies
        run: moon run :install
        
      - name: Test all projects
        run: moon run :test
        
      - name: Build all projects
        run: moon run :build 