name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pull-requests: write  # Needed to comment coverage results on PRs

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Proto
        uses: moonrepo/setup-proto@v1
        
      - name: Install Moon
        run: proto install moon
        
      - name: Install Bun
        run: proto install bun
        
      - name: Install dependencies
        run: moon run :install
        
      - name: Generate coverage for server
        run: moon run cursed-server:coverage
        
      - name: Generate coverage for web
        run: moon run cursed-web:coverage
        
      - name: Upload coverage to Codecov
        id: codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cursed-server/coverage/lcov.info,./cursed-web/coverage/lcov.info
          flags: server,web
          fail_ci_if_error: true
          
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            ## Coverage Report
            
            | Component | Coverage |
            | --- | --- |
            | Server | ${{ steps.codecov.outputs.server }}% |
            | Web | ${{ steps.codecov.outputs.web }}% |
            
            [View detailed report on Codecov](https://codecov.io/gh/${{ github.repository }}/pull/${{ github.event.pull_request.number }}) 