name: Docker Build & Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cursed-server, cursed-web]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Proto
        uses: moonrepo/setup-proto@v1
        
      - name: Install Moon
        run: proto install moon
        
      - name: Install dependencies
        run: moon run :install
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
          
      - name: Run Docker build
        run: moon run ${{ matrix.service }}:docker-build
        
      - name: Tag Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker tag ${{ matrix.service }}:latest ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ steps.meta.outputs.version }}
          docker tag ${{ matrix.service }}:latest ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest
          
      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ steps.meta.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest 